version: "3.8"

services:

    data:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=yourStrongPassword12!@
        volumes:
            - sqldata:/var/opt/mssql
        networks:
            - dentalsystem-network

    messages:
        container_name: rabbitmq
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
        hostname: "rabbitmq"
        environment:
            - RABBITMQ_DEFAULT_USER=rabbitmquser
            - RABBITMQ_DEFAULT_PASS=rabbitmqPassword12!
        volumes:
            - rabbitmq:/var/lib/rabbitmq/mnesia
        networks:
            - dentalsystem-network

    identity:
        container_name: identity
        image: stoian/dentalsystem-identity-service
        build:
            context: ./Server
            dockerfile: ./DentalSystem.Identity/Dockerfile
        ports:
            - "5001:80"
        env_file: Server/DentalSystem/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DentalSystem_IdentityDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
            - IdentitySettings__AdminPassword=adminpass12!
            - MessageQueueSettings__Host=rabbitmq
            - MessageQueueSettings__UserName=rabbitmquser
            - MessageQueueSettings__Password=rabbitmqPassword12!
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks:
            - dentalsystem-network
        depends_on:
            - data

    scheduling:
        container_name: scheduling
        image: stoian/dentalsystem-scheduling-service
        build:
            context: ./Server
            dockerfile: ./DentalSystem.Scheduling/Dockerfile
        ports:
            - "5002:80"
        env_file: Server/DentalSystem/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DentalSystem_SchedulingDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
            - ConnectionStrings__CronJobsConnection=Server=sqlserver;Database=DentalSystem_SchedulingCronJobDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
            - MessageQueueSettings__Host=rabbitmq
            - MessageQueueSettings__UserName=rabbitmquser
            - MessageQueueSettings__Password=rabbitmqPassword12!
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks:
            - dentalsystem-network
        depends_on:
            - data

    watchdog:
        container_name: watchdog
        image: stoian/dentalsystem-watchdog-service
        build:
            context: ./Server
            dockerfile: ./DentalSystem.Watchdog/Dockerfile
        ports:
            - "5500:80"
        environment:
            - HealthChecks-UI__HealthChecks__0__Name=Identity
            - HealthChecks-UI__HealthChecks__0__Uri=http://identity/health
            - HealthChecks-UI__HealthChecks__1__Name=Scheduling
            - HealthChecks-UI__HealthChecks__1__Uri=http://scheduling/health
        restart: on-failure
        networks:
            - dentalsystem-network
        depends_on:
            - identity

networks:
    dentalsystem-network:

volumes:
    sqldata:
    rabbitmq:
    data-protection:
